Repository emberjs/ember-test-helpers, pull requests merged in 2018-12, with the labels that each got.

#491 TravisCI: Remove deprecated `sudo: false` option
  .travis.yml
Labels: internal

#497 Only customize RSVP's async for Ember < 1.7.
  addon-test-support/ember-test-helpers/legacy-0-6-x/ext/rsvp.js
Labels: bug

#498 Add ability to opt-out of automatic settledness waiting in teardown.
  addon-test-support/@ember/test-helpers/teardown-application-context.ts
  addon-test-support/@ember/test-helpers/teardown-context.ts
  addon-test-support/@ember/test-helpers/teardown-rendering-context.ts
  tests/helpers/manual-test-waiter.js
  tests/unit/teardown-context-test.js
  tests/unit/teardown-rendering-context-test.js
Labels: enhancement

#505 Update dependency on ember-cli-htmlbars-inline-precompile to ^2.1.0.
  package.json
  yarn.lock
Labels: enhancement
