Repository emberjs/ember-test-helpers, pull requests merged in 2018-02, with the labels that each got.

#305 Support testing without an application template wrapper.
  .travis.yml
  addon-test-support/@ember/test-helpers/setup-application-context.js
  addon-test-support/@ember/test-helpers/setup-rendering-context.js
  addon-test-support/ember-test-helpers/legacy-0-6-x/test-module-for-component.js
  config/ember-try.js
  package.json
  tests/integration/setup-rendering-context-test.js
  tests/unit/setup-rendering-context-test.js
  yarn.lock
Labels: enhancement

#317 Remove simple alias for `wait` -> `settled`.
  addon-test-support/@ember/test-helpers/settled.js
  addon-test-support/ember-test-helpers/wait.js
  tests/integration/settled-test.js
  tests/unit/wait-test.js
Labels: bug

#320 Lock down documentation to 5.3.5 to avoid Node 4 issues.
  package.json
  yarn.lock
Labels: internal

#319 Fix regression with `wait()` timeouts.
  addon-test-support/ember-test-helpers/wait.js
Labels: bug
