Repository emberjs/ember-test-helpers, pull requests merged in 2018-11, with the labels that each got.

#449 CI: Only run for `master`, PRs and version tags and branches
  .travis.yml
Labels: internal

#450 Convert to TypeScript
  .eslintrc.js
  addon-test-support/@ember/test-helpers/-utils.ts
  addon-test-support/@ember/test-helpers/application.ts
  addon-test-support/@ember/test-helpers/build-owner.ts
  addon-test-support/@ember/test-helpers/dom/-get-element.ts
  addon-test-support/@ember/test-helpers/dom/-get-elements.ts
  addon-test-support/@ember/test-helpers/dom/-is-focusable.ts
  addon-test-support/@ember/test-helpers/dom/-is-form-control.ts
  addon-test-support/@ember/test-helpers/dom/-to-array.ts
  addon-test-support/@ember/test-helpers/dom/blur.ts
  addon-test-support/@ember/test-helpers/dom/click.ts
  addon-test-support/@ember/test-helpers/dom/double-click.ts
  addon-test-support/@ember/test-helpers/dom/fill-in.ts
  addon-test-support/@ember/test-helpers/dom/find-all.ts
  addon-test-support/@ember/test-helpers/dom/find.ts
  addon-test-support/@ember/test-helpers/dom/fire-event.ts
  addon-test-support/@ember/test-helpers/dom/focus.ts
  addon-test-support/@ember/test-helpers/dom/get-root-element.ts
  addon-test-support/@ember/test-helpers/dom/tap.ts
  addon-test-support/@ember/test-helpers/dom/trigger-event.ts
  addon-test-support/@ember/test-helpers/dom/trigger-key-event.ts
  addon-test-support/@ember/test-helpers/dom/type-in.ts
  addon-test-support/@ember/test-helpers/dom/wait-for.ts
  addon-test-support/@ember/test-helpers/global.ts
  addon-test-support/@ember/test-helpers/has-ember-version.ts
  addon-test-support/@ember/test-helpers/index.ts
  addon-test-support/@ember/test-helpers/resolver.ts
  addon-test-support/@ember/test-helpers/settled.ts
  addon-test-support/@ember/test-helpers/setup-application-context.ts
  addon-test-support/@ember/test-helpers/setup-context.ts
  addon-test-support/@ember/test-helpers/setup-rendering-context.ts
  addon-test-support/@ember/test-helpers/teardown-application-context.ts
  addon-test-support/@ember/test-helpers/teardown-context.ts
  addon-test-support/@ember/test-helpers/teardown-rendering-context.ts
  addon-test-support/@ember/test-helpers/validate-error-handler.ts
  addon-test-support/@ember/test-helpers/wait-until.ts
  addon-test-support/ember-test-helpers/index.d.ts
  index.js
  package.json
  scripts/move-declaration-files.js
  scripts/precompile.sh
  tests/dummy/app/config/environment.d.ts
  tsconfig.json
  types/dummy/index.d.ts
  types/ember-data/types/registries/model.d.ts
  yarn.lock
Labels: enhancement

#456 tests: Adjust import paths to use `@ember/test-helpers`
  tests/helpers/resolver.js
  tests/integration/settled-test.js
  tests/integration/setup-rendering-context-test.js
  tests/unit/dom/blur-test.js
  tests/unit/dom/click-test.js
  tests/unit/dom/double-click-test.js
  tests/unit/dom/fill-in-test.js
  tests/unit/dom/find-all-test.js
  tests/unit/dom/find-test.js
  tests/unit/dom/focus-test.js
  tests/unit/dom/get-root-element-test.js
  tests/unit/dom/select-files-test.js
  tests/unit/dom/tap-test.js
  tests/unit/dom/trigger-event-test.js
  tests/unit/dom/trigger-key-event-test.js
  tests/unit/dom/type-in-test.js
  tests/unit/dom/wait-for-test.js
  tests/unit/settled-test.js
  tests/unit/setup-application-context-test.js
  tests/unit/setup-context-test.js
  tests/unit/setup-rendering-context-test.js
  tests/unit/teardown-context-test.js
  tests/unit/teardown-rendering-context-test.js
Labels: internal

#458 Adds a basic failing test for `settled`
  .travis.yml
  addon-test-support/@ember/test-helpers/-utils.ts
  addon-test-support/@ember/test-helpers/wait-until.ts
  tests/integration/settled-test.js
Labels: bug

#462 Improve ESLint usage
  .eslintignore
  .eslintrc.js
  .gitignore
  addon-test-support/@ember/test-helpers/-utils.ts
  addon-test-support/@ember/test-helpers/setup-rendering-context.ts
  package.json
Labels: internal

#452 Import type definitions from `@types/ember__test-helpers`
  addon-test-support/@ember/test-helpers/-utils.ts
  addon-test-support/@ember/test-helpers/application.ts
  addon-test-support/@ember/test-helpers/dom/-target.ts
  addon-test-support/@ember/test-helpers/dom/blur.ts
  addon-test-support/@ember/test-helpers/dom/click.ts
  addon-test-support/@ember/test-helpers/dom/double-click.ts
  addon-test-support/@ember/test-helpers/dom/fill-in.ts
  addon-test-support/@ember/test-helpers/dom/find-all.ts
  addon-test-support/@ember/test-helpers/dom/find.ts
  addon-test-support/@ember/test-helpers/dom/focus.ts
  addon-test-support/@ember/test-helpers/dom/get-root-element.ts
  addon-test-support/@ember/test-helpers/dom/tap.ts
  addon-test-support/@ember/test-helpers/dom/trigger-event.ts
  addon-test-support/@ember/test-helpers/dom/trigger-key-event.ts
  addon-test-support/@ember/test-helpers/dom/type-in.ts
  addon-test-support/@ember/test-helpers/dom/wait-for.ts
  addon-test-support/@ember/test-helpers/resolver.ts
  addon-test-support/@ember/test-helpers/settled.ts
  addon-test-support/@ember/test-helpers/setup-application-context.ts
  addon-test-support/@ember/test-helpers/setup-context.ts
  addon-test-support/@ember/test-helpers/setup-rendering-context.ts
  addon-test-support/@ember/test-helpers/teardown-application-context.ts
  addon-test-support/@ember/test-helpers/teardown-context.ts
  addon-test-support/@ember/test-helpers/teardown-rendering-context.ts
  addon-test-support/@ember/test-helpers/wait-until.ts
Labels: enhancement

#464 Add *.ts to `.npmignore`.
  .npmignore
Labels: internal

#466 Fix precompile errors and prevent regressions.
  addon-test-support/@ember/test-helpers/-utils.ts
  package.json
Labels: internal

#463 Improve type declarations
  addon-test-support/@ember/test-helpers/-tuple.ts
  addon-test-support/@ember/test-helpers/-utils.ts
  addon-test-support/@ember/test-helpers/application.ts
  addon-test-support/@ember/test-helpers/build-owner.ts
  addon-test-support/@ember/test-helpers/dom/-get-element.ts
  addon-test-support/@ember/test-helpers/dom/-get-elements.ts
  addon-test-support/@ember/test-helpers/dom/-is-focusable.ts
  addon-test-support/@ember/test-helpers/dom/-is-form-control.ts
  addon-test-support/@ember/test-helpers/dom/-target.ts
  addon-test-support/@ember/test-helpers/dom/-to-array.ts
  addon-test-support/@ember/test-helpers/dom/blur.ts
  addon-test-support/@ember/test-helpers/dom/click.ts
  addon-test-support/@ember/test-helpers/dom/double-click.ts
  addon-test-support/@ember/test-helpers/dom/fire-event.ts
  addon-test-support/@ember/test-helpers/dom/focus.ts
  addon-test-support/@ember/test-helpers/dom/get-root-element.ts
  addon-test-support/@ember/test-helpers/dom/trigger-key-event.ts
  addon-test-support/@ember/test-helpers/dom/type-in.ts
  addon-test-support/@ember/test-helpers/dom/wait-for.ts
  addon-test-support/@ember/test-helpers/has-ember-version.ts
  addon-test-support/@ember/test-helpers/resolver.ts
  addon-test-support/@ember/test-helpers/settled.ts
  addon-test-support/@ember/test-helpers/setup-application-context.ts
  addon-test-support/@ember/test-helpers/setup-context.ts
  addon-test-support/@ember/test-helpers/setup-rendering-context.ts
  addon-test-support/@ember/test-helpers/teardown-context.ts
  addon-test-support/@ember/test-helpers/teardown-rendering-context.ts
  addon-test-support/@ember/test-helpers/wait-until.ts
  tsconfig.json
  types/ember-test-helpers/legacy-0-6-x/build-registry.d.ts
Labels: enhancement

#480 Extract Prettier configuration to .prettierrc.js file.
  .eslintrc.js
  .gitignore
  .prettierrc.js
Labels: internal
