Repository emberjs/ember-test-helpers, pull requests merged in 2018-03, with the labels that each got.

#334 Enhance README and API reference
  API.md
  README.md
  documentation.yml
Labels: documentation

#344 Update `qunit` to v2.5.1
  package.json
  tests/helpers/events.js
  tests/unit/dom/blur-test.js
  tests/unit/dom/click-test.js
  tests/unit/dom/fill-in-test.js
  tests/unit/dom/focus-test.js
  tests/unit/dom/tap-test.js
  tests/unit/dom/trigger-event-test.js
  tests/unit/dom/trigger-key-event-test.js
  yarn.lock
Labels: internal

#336 make getApplication public
  API.md
  addon-test-support/@ember/test-helpers/index.js
  tests/unit/application-test.js
Labels: enhancement

#346 Allow for custom error message in waitUntil helper
  addon-test-support/@ember/test-helpers/wait-until.js
  tests/unit/wait-until-test.js
Labels: enhancement

#348 wait-for helper's count value is null by default.
  API.md
  addon-test-support/@ember/test-helpers/dom/wait-for.js
Labels: documentation

#349 Protect context properties and methods from overwriting
  addon-test-support/@ember/test-helpers/setup-context.js
  addon-test-support/@ember/test-helpers/setup-rendering-context.js
  tests/unit/setup-context-test.js
  tests/unit/setup-rendering-context-test.js
Labels: enhancement
