Repository emberjs/ember-test-helpers, pull requests merged in 2020-10, with the labels that each got.

#924 Ensure setting an empty `value` in FileInput clears the selected files
  addon-test-support/@ember/test-helpers/dom/fire-event.ts
  tests/unit/dom/select-files-test.js
Labels: bug

#925 Update release setup.
  RELEASE.md
  package.json
  yarn.lock
Labels: internal

#926 Add `scrollTo` and `select` to API documentation.
  API.md
  documentation.yml
Labels: documentation
