Repository emberjs/ember-test-helpers, pull requests merged in 2020-04, with the labels that each got.

#775 Drop support for Node 8
  .travis.yml
  package.json
Labels: breaking

#798 CI: Add test scenarios for Ember 3.8, 3.12 and 3.16
  .travis.yml
  config/ember-try.js
Labels: internal

#799 Drop Support for Ember 3.7 and below
  .travis.yml
  config/ember-try.js
Labels: breaking

#800 Update eslint-typescript packages
  .eslintrc.js
  package.json
  yarn.lock
Labels: internal

#801 README: Add "Compatibility" section
  README.md
Labels: documentation

#802 Remove obsolete yarn `resolutions`
  package.json
  yarn.lock
Labels: internal

#814 Re-roll yarn.lock.
  yarn.lock
Labels: internal

#698 Add `scrollTo` helper
  addon-test-support/@ember/test-helpers/dom/scroll-to.ts
  addon-test-support/@ember/test-helpers/index.ts
  tests/integration/dom/scroll-to-test.js
Labels: enhancement

#741 Respect "disabled" in "fillIn" and "typeIn"
  addon-test-support/@ember/test-helpers/dom/-is-focusable.ts
  addon-test-support/@ember/test-helpers/dom/-target.ts
  addon-test-support/@ember/test-helpers/dom/fill-in.ts
  addon-test-support/@ember/test-helpers/dom/type-in.ts
  tests/unit/dom/fill-in-test.js
  tests/unit/dom/type-in-test.js
Labels: bug

#778 [breaking] disable interacting with disabled form controls
  addon-test-support/@ember/test-helpers/dom/blur.ts
  addon-test-support/@ember/test-helpers/dom/click.ts
  addon-test-support/@ember/test-helpers/dom/double-click.ts
  addon-test-support/@ember/test-helpers/dom/focus.ts
  addon-test-support/@ember/test-helpers/dom/tap.ts
  addon-test-support/@ember/test-helpers/dom/trigger-event.ts
  addon-test-support/@ember/test-helpers/dom/trigger-key-event.ts
  tests/unit/dom/click-test.js
  tests/unit/dom/double-click-test.js
  tests/unit/dom/focus-test.js
  tests/unit/dom/tap-test.js
  tests/unit/dom/trigger-event-test.js
  tests/unit/dom/trigger-key-event-test.js
Labels: breaking

#818 Remove `ember-test-helpers/wait`.
  addon-test-support/ember-test-helpers/wait.js
  tests/unit/legacy-0-6-x/test-module-for-component-test.js
  tests/unit/wait-test.js
Labels: breaking

#820 Remove ember-assign-polyfill dependency.
  package.json
  yarn.lock
Labels: internal

#819 Move buildRegistry into `@ember/test-helpers/-internals`.
  addon-test-support/@ember/test-helpers/-internal/build-registry.ts
  addon-test-support/@ember/test-helpers/build-owner.ts
  addon-test-support/ember-test-helpers/legacy-0-6-x/build-registry.js
  addon-test-support/ember-test-helpers/legacy-0-6-x/test-module.js
  types/ember-test-helpers/legacy-0-6-x/build-registry.d.ts
  types/require.d.ts
Labels: internal

#821 Remove ember-cli-htmlbars-inline-precompile.
  addon-test-support/@ember/test-helpers/setup-rendering-context.ts
  index.js
  package.json
  tests/integration/dom/scroll-to-test.js
  tests/integration/module-for-acceptance-interop-test.js
  tests/integration/settled-test.js
  tests/integration/setup-rendering-context-test.js
  tests/unit/dom/logging-test.js
  tests/unit/legacy-0-6-x/test-module-for-acceptance-test.js
  tests/unit/legacy-0-6-x/test-module-for-component-test.js
  tests/unit/setup-application-context-test.js
  tests/unit/setup-rendering-context-test.js
  yarn.lock
Labels: internal

#822 Remove `moduleFor`, `moduleForComponent`, `moduleForModel`, `moduleForAcceptance` support.
  addon-test-support/ember-test-helpers/index.d.ts
  addon-test-support/ember-test-helpers/index.js
  addon-test-support/ember-test-helpers/legacy-0-6-x/-legacy-overrides.js
  addon-test-support/ember-test-helpers/legacy-0-6-x/abstract-test-module.js
  addon-test-support/ember-test-helpers/legacy-0-6-x/ext/rsvp.js
  addon-test-support/ember-test-helpers/legacy-0-6-x/test-module-for-acceptance.js
  addon-test-support/ember-test-helpers/legacy-0-6-x/test-module-for-component.js
  addon-test-support/ember-test-helpers/legacy-0-6-x/test-module-for-model.js
  addon-test-support/ember-test-helpers/legacy-0-6-x/test-module.js
  tests/integration/module-for-acceptance-interop-test.js
  tests/unit/legacy-0-6-x/test-module-for-acceptance-test.js
  tests/unit/legacy-0-6-x/test-module-for-component-test.js
  tests/unit/legacy-0-6-x/test-module-for-model-test.js
  tests/unit/legacy-0-6-x/test-module-test.js
Labels: breaking

#824 Migrate CI to GitHub Actions.
  .github/workflows/ci-build.yml
  .travis.yml
  README.md
  package.json
Labels: internal

#685 Default `click` and `doubleClick` to be left button clicks.
  addon-test-support/@ember/test-helpers/dom/click.ts
  addon-test-support/@ember/test-helpers/dom/double-click.ts
  tests/unit/dom/click-test.js
  tests/unit/dom/double-click-test.js
Labels: bug

#825 Remove deprecation for `files` array with `triggerEvent`.
  addon-test-support/@ember/test-helpers/dom/fire-event.ts
  tests/unit/dom/select-files-test.js
Labels: breaking

#826 Remove deprecated `this.$` from `setupRenderingContext`.
  addon-test-support/@ember/test-helpers/setup-rendering-context.ts
  tests/unit/setup-rendering-context-test.js
Labels: breaking

#830 Increase browser start timeout.
  testem.js
Labels: internal

#831 Refactor ember-try scenarios.
  .eslintrc.js
  .github/workflows/ci-build.yml
  config/ember-try.js
  package.json
  tests/dummy/config/optional-features.json
  tests/unit/setup-rendering-context-test.js
Labels: internal

#832 Remove ember-debug-handlers-polyfill.
  package.json
  yarn.lock
Labels: internal
