Repository emberjs/ember-test-helpers, pull requests merged in 2021-08, with the labels that each got.

#1071 Expose deprecation primitives
  API.md
  addon-test-support/@ember/test-helpers/-internal/deprecations.ts
  addon-test-support/@ember/test-helpers/index.ts
  addon-test-support/@ember/test-helpers/setup-context.ts
  tests/test-helper.js
  tests/unit/setup-context-test.js
Labels: enhancement

#1081 timeout GH Actions jobs after 10 minutes
  .github/workflows/ci-build.yml
Labels: internal

#1078 Expose warning management primitives
  API.md
  addon-test-support/@ember/test-helpers/-internal/deprecations.ts
  addon-test-support/@ember/test-helpers/-internal/is-promise.ts
  addon-test-support/@ember/test-helpers/-internal/warnings.ts
  addon-test-support/@ember/test-helpers/index.ts
  addon-test-support/@ember/test-helpers/setup-context.ts
  tests/unit/-internal/is-promise-test.js
  tests/unit/setup-context-test.js
Labels: enhancement

#1101 Bring back `{{#in-element}}` test in ember-classic
  tests/integration/setup-rendering-context-test.js
Labels: internal

#1102 Pin release-it to 14.10.1 due to Node 10 incompatiblities
  package.json
  yarn.lock
Labels: internal

#1104 Fixes tarball to include correct contents
  .npmignore
  package.json
Labels: internal

#1109 Upgrade @ember/test-waiters to 3.0.0
  .github/workflows/ci-build.yml
  config/ember-try.js
  package.json
  yarn.lock
Labels: dependencies

#1110 [FIX] This fixes ember-canary
  addon-test-support/@ember/test-helpers/setup-rendering-context.ts
Labels: bug

#1111 Fixes postpack script to cleanup correct file type
  package.json
Labels: bug
