Repository emberjs/ember-test-helpers, pull requests merged in 2021-02, with the labels that each got.

#987 Support getOwner
  addon-test-support/@ember/test-helpers/setup-context.ts
  tests/unit/setup-rendering-context-test.js
Labels: enhancement

#988 Bumping version of `@ember/test-waiters` to avoid issues in Embroider builds
  package.json
  yarn.lock
Labels: internal

#992 Inline promise polyfill fallback.
  .eslintrc.js
  addon-test-support/@ember/test-helpers/-internal/promise-polyfill.d.ts
  addon-test-support/@ember/test-helpers/-internal/promise-polyfill.js
  addon-test-support/@ember/test-helpers/-utils.ts
  package.json
  tests/test-helper.js
  yarn.lock
Labels: bug

#995 Correctly handle resetOnerror
  addon-test-support/@ember/test-helpers/setup-onerror.ts
  tests/unit/setup-ember-onerror-test.js
Labels: bug
