Repository emberjs/ember-test-helpers, pull requests merged in 2022-12, with the labels that each got.

#1280 Update lockfile to latest `@babel/*` deps
  addon-test-support/@ember/test-helpers/setup-application-context.ts
  addon-test-support/@ember/test-helpers/setup-rendering-context.ts
  package.json
  type-tests/api.ts
  type-tests/tsconfig.json
  yarn.lock
Labels: dependencies

#1271 Upgrade ember v3.27.0...v4.9.2 (in development)
  .ember-cli
  .eslintignore
  .github/workflows/ci-build.yml
  .gitignore
  .npmignore
  .prettierignore
  .travis.yml
  CONTRIBUTING.md
  README.md
  config/environment.js
  ember-cli-build.js
  package.json
  tests/dummy/app/index.html
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  tests/index.html
  yarn.lock
Labels: enhancement, breaking

#1283 Fix types versions
  package.json
Labels: bug

#1284 Ensure types reflect optional-ness of tab options
  API.md
  addon-test-support/@ember/test-helpers/dom/tab.ts
  package.json
  type-tests/api.ts
Labels: bug, Backport to 2.x

#1288 Correctly handle special char keyCodes with Shift
  addon-test-support/@ember/test-helpers/dom/trigger-key-event.ts
  tests/unit/dom/trigger-key-event-test.js
Labels: bug, Backport to 2.x

#1286 Upgrade expect-type; fix issues it reveals; add RenderingTestContext
  API.md
  addon-test-support/@ember/test-helpers/dom/fill-in.ts
  addon-test-support/@ember/test-helpers/dom/tap.ts
  addon-test-support/@ember/test-helpers/index.ts
  addon-test-support/@ember/test-helpers/setup-rendering-context.ts
  package.json
  type-tests/api.ts
  yarn.lock
Labels: bug, enhancement, Backport to 2.x

#1285 Export type for Target
  addon-test-support/@ember/test-helpers/index.ts
  type-tests/api.ts
Labels: bug, Backport to 2.x

#1287 Port some conveniences from @types/ember__test-helpers package
  addon-test-support/@ember/test-helpers/dom/-get-element.ts
  addon-test-support/@ember/test-helpers/dom/find-all.ts
  addon-test-support/@ember/test-helpers/dom/find.ts
  addon-test-support/@ember/test-helpers/dom/trigger-event.ts
  addon-test-support/@ember/test-helpers/settled.ts
  addon-test-support/@ember/test-helpers/setup-context.ts
  type-tests/api.ts
Labels: bug, Backport to 2.x

#1272 Use ember preview types
  addon-test-support/@ember/test-helpers/-internal/build-registry.ts
  addon-test-support/@ember/test-helpers/build-owner.ts
  addon-test-support/@ember/test-helpers/resolver.ts
  addon-test-support/@ember/test-helpers/settled.ts
  addon-test-support/@ember/test-helpers/setup-context.ts
  package.json
  tsconfig.json
  type-tests/api.ts
  type-tests/tsconfig.json
  types/dummy/index.d.ts
  yarn.lock
Labels: enhancement

#1291 Remove deprecations targeting v3.0.0
  addon-test-support/@ember/test-helpers/setup-rendering-context.ts
  tests/unit/setup-rendering-context-test.js
Labels: breaking

#1292 Make ember-auto-import@2 a dependency
  package.json
Labels: breaking

#1294 Update volta-cli/action to v4
  .github/workflows/ci-build.yml
Labels: internal

#1295 Drop support for IE11 (require native Promise)
  addon-test-support/@ember/test-helpers/-internal/helper-hooks.ts
  addon-test-support/@ember/test-helpers/-internal/promise-polyfill.ts
  addon-test-support/@ember/test-helpers/-utils.ts
  addon-test-support/@ember/test-helpers/build-owner.ts
  addon-test-support/@ember/test-helpers/dom/blur.ts
  addon-test-support/@ember/test-helpers/dom/click.ts
  addon-test-support/@ember/test-helpers/dom/double-click.ts
  addon-test-support/@ember/test-helpers/dom/fill-in.ts
  addon-test-support/@ember/test-helpers/dom/focus.ts
  addon-test-support/@ember/test-helpers/dom/scroll-to.ts
  addon-test-support/@ember/test-helpers/dom/select.ts
  addon-test-support/@ember/test-helpers/dom/tab.ts
  addon-test-support/@ember/test-helpers/dom/tap.ts
  addon-test-support/@ember/test-helpers/dom/trigger-event.ts
  addon-test-support/@ember/test-helpers/dom/trigger-key-event.ts
  addon-test-support/@ember/test-helpers/dom/type-in.ts
  addon-test-support/@ember/test-helpers/dom/wait-for.ts
  addon-test-support/@ember/test-helpers/settled.ts
  addon-test-support/@ember/test-helpers/setup-application-context.ts
  addon-test-support/@ember/test-helpers/setup-context.ts
  addon-test-support/@ember/test-helpers/setup-rendering-context.ts
  addon-test-support/@ember/test-helpers/teardown-context.ts
  addon-test-support/@ember/test-helpers/wait-until.ts
  tests/test-helper.js
Labels: breaking

#1293 Drop support for Ember 3.x
  .github/workflows/ci-build.yml
  README.md
  package.json
  tests/dummy/config/ember-try.js
Labels: breaking

#1167 Remove ember-test-helpers.setup-rendering-context.render && clearRender deprecation
  addon-test-support/@ember/test-helpers/setup-rendering-context.ts
  tests/unit/setup-rendering-context-test.js
Labels: breaking

#1297 Add support for TS 4.8 and 4.9
  .github/workflows/ci-build.yml
  README.md
Labels: enhancement

#1299 Remove IE11 support code
  addon-test-support/@ember/test-helpers/dom/find-all.ts
  addon-test-support/@ember/test-helpers/dom/trigger-key-event.ts
  addon-test-support/@ember/test-helpers/dom/wait-for.ts
  addon-test-support/@ember/test-helpers/ie-11-polyfills.ts
  tests/helpers/browser-detect.js
  tests/unit/dom/blur-test.js
  tests/unit/dom/click-test.js
  tests/unit/dom/double-click-test.js
  tests/unit/dom/fill-in-test.js
  tests/unit/dom/focus-test.js
  tests/unit/dom/select-test.js
  tests/unit/dom/tab-test.js
  tests/unit/dom/tap-test.js
  tests/unit/dom/type-in-test.js
Labels: internal

#1303 `TestContext.resumeTest()` returns `void`, not `Promise<void>`
  addon-test-support/@ember/test-helpers/setup-context.ts
Labels: bug

#1302 [backport] Remove the index signature from `TestContext`
  addon-test-support/@ember/test-helpers/setup-context.ts
  addon-test-support/@ember/test-helpers/setup-rendering-context.ts
Labels: bug

#1304 Avoid unnecessary dependencies on `@glimmer` types
  addon-test-support/@ember/test-helpers/-internal/get-component-manager.ts
  addon-test-support/@ember/test-helpers/setup-rendering-context.ts
  type-tests/api.ts
Labels: bug, Backport to 2.x

#1305 [backport] Avoid unnecessary dependencies on `@glimmer` types
  addon-test-support/@ember/test-helpers/-internal/get-component-manager.ts
  addon-test-support/@ember/test-helpers/setup-rendering-context.ts
  type-tests/api.ts
Labels: bug
