Repository emberjs/ember-test-helpers, pull requests merged in 2023-06, with the labels that each got.

#1401 fixing the release
  addon/.npmignore
  addon/package.json
  addon/types.tsconfig.json
Labels: bug

#1410 Updates that address missing files in published package
  addon/.npmignore
  addon/APACHE-LICENSE.md
  addon/MIT-LICENSE.md
Labels: bug

#1413 Update addon/.gitignore
  addon/.gitignore
Labels: internal

#1416 Add support for TS 5.0 and 5.1
  .github/workflows/ci-build.yml
Labels: enhancement

#1417 bugfix: handle `null` and `undefined` in `setProperties`
  addon/addon-test-support/@ember/test-helpers/setup-context.ts
  addon/tests/unit/setup-context-test.js
Labels: bug, Backport to 2.x

#1411 adds new workflow file to provide release branches
  .github/workflows/push-dist.yml
Labels: enhancement

#1418 (backport) bugfix: handle `null` and `undefined` in `setProperties`
  addon-test-support/@ember/test-helpers/setup-context.ts
  tests/unit/setup-context-test.js
Labels: bug, Backport to 2.x

#1389 Support `@types`, preview types, and stable types for Ember.js
  .github/workflows/ci-build.yml
  addon/.eslintrc.js
  addon/addon-test-support/@ember/test-helpers/-internal/-owner-mixin-imports.ts
  addon/addon-test-support/@ember/test-helpers/-internal/build-registry.ts
  addon/addon-test-support/@ember/test-helpers/-internal/debug-info.ts
  addon/addon-test-support/@ember/test-helpers/-internal/is-component.ts
  addon/addon-test-support/@ember/test-helpers/build-owner.ts
  addon/addon-test-support/@ember/test-helpers/index.ts
  addon/addon-test-support/@ember/test-helpers/settled.ts
  addon/addon-test-support/@ember/test-helpers/setup-context.ts
  addon/package.json
  addon/tests/dummy/config/ember-try.js
  addon/types/dummy/index.d.ts
  addon/types/virtual.d.ts
  yarn.lock
Labels: enhancement
