Repository emberjs/ember-test-helpers, pull requests merged in 2023-01, with the labels that each got.

#1320 Don't swallow deprecations and warnings when there is no test context
  addon-test-support/@ember/test-helpers/setup-context.ts
Labels: bug

#1318 [DOC] Swap `find` and `findAll` examples
  API.md
  addon-test-support/@ember/test-helpers/dom/find-all.ts
  addon-test-support/@ember/test-helpers/dom/find.ts
Labels: documentation

#1324 Use node 16 for development instead of node 14
  package.json
Labels: internal
