Repository emberjs/ember-test-helpers, pull requests merged in 2023-05, with the labels that each got.

#1387 Pass owner instead of registry to ember-data's setupContainer
  addon/addon-test-support/@ember/test-helpers/-internal/build-registry.ts
Labels: v3

#1361 Sync with the v2.x branch
  addon/CHANGELOG.md
  addon/package.json
Labels: v3

#1380 Use sibling import for logging so that these files are rollup compatible
  addon/addon-test-support/@ember/test-helpers/dom/blur.ts
  addon/addon-test-support/@ember/test-helpers/dom/click.ts
  addon/addon-test-support/@ember/test-helpers/dom/double-click.ts
  addon/addon-test-support/@ember/test-helpers/dom/fill-in.ts
  addon/addon-test-support/@ember/test-helpers/dom/fire-event.ts
  addon/addon-test-support/@ember/test-helpers/dom/focus.ts
  addon/addon-test-support/@ember/test-helpers/dom/tap.ts
  addon/addon-test-support/@ember/test-helpers/dom/trigger-event.ts
  addon/addon-test-support/@ember/test-helpers/dom/trigger-key-event.ts
  addon/addon-test-support/@ember/test-helpers/dom/type-in.ts
Labels: internal, v3

#1378 ensureSafeComponent is not needed on Ember > 3.25
  addon/addon-test-support/@ember/test-helpers/setup-rendering-context.ts
  addon/package.json
  yarn.lock
Labels: v3

#1384 Remove extraneous event-dispatcher wiring and a amd/require
  addon/tests/helpers/resolver.js
Labels: breaking, v3

#1379 remove has-ember-version
  addon/addon-test-support/ember-test-helpers/has-ember-version.ts
Labels: breaking, v3

#1396 Update .npmignore
  addon/.npmignore
Labels: internal, v3

#1382 Remove code for pre-ember-v4
  addon/addon-test-support/@ember/test-helpers/-internal/get-component-manager.ts
  addon/addon-test-support/@ember/test-helpers/-internal/is-component.ts
  addon/addon-test-support/@ember/test-helpers/-internal/render-settled.ts
  addon/addon-test-support/@ember/test-helpers/setup-rendering-context.ts
  addon/tests/integration/dom/scroll-to-test.js
  addon/types/virtual.d.ts
Labels: v3
