Repository emberjs/ember-test-helpers, pull requests merged in 2024-07, with the labels that each got.

#1455 Pin isbinaryfile (a sub-sub dependency) so we can keep node support
  package.json
  yarn.lock
Labels: internal

#1457 Expand TypeScript test matrix
  .github/workflows/ci-build.yml
Labels: internal

#1454 Test against ember LTS 5.4, and, 5.8
  .github/workflows/ci-build.yml
  addon/tests/dummy/config/ember-try.js
Labels: internal

#1456 Fix: You attempted to render a path ({{model.post_id}}), but model was not in scope:
  addon/tests/unit/setup-application-context-test.js
Labels: internal

#1449 this change makes it so strict package managers installing duplicate …
  addon/addon-test-support/@ember/test-helpers/dom/fill-in.ts
  addon/addon-test-support/@ember/test-helpers/setup-context.ts
  package.json
  yarn.lock
Labels: bug

#1451 Update `git clone` command in README.md under contribution
  README.md
Labels: documentation

#1460 Setup release plan
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  CHANGELOG.md
  RELEASE.md
  addon/RELEASE.md
  package.json
  pnpm-lock.yaml
Labels: internal

#1464 Use the right attribute - `maxlength` instead of `maxLength`
  addon/addon-test-support/@ember/test-helpers/dom/-guard-for-maxlength.ts
Labels: bug

#1462 correct git clone url for the repo
  CONTRIBUTING.md
Labels: documentation

#1467 Fix import type via upgrading @tsconfig/ember
  .github/workflows/ci-build.yml
  addon/addon-test-support/@ember/test-helpers/-internal/build-registry.ts
  addon/addon-test-support/@ember/test-helpers/-internal/debug-info.ts
  addon/addon-test-support/@ember/test-helpers/-internal/deprecations.ts
  addon/addon-test-support/@ember/test-helpers/-internal/warnings.ts
  addon/addon-test-support/@ember/test-helpers/build-owner.ts
  addon/addon-test-support/@ember/test-helpers/dom/-get-description.ts
  addon/addon-test-support/@ember/test-helpers/dom/-get-element.ts
  addon/addon-test-support/@ember/test-helpers/dom/-get-window-or-element.ts
  addon/addon-test-support/@ember/test-helpers/dom/-guard-for-maxlength.ts
  addon/addon-test-support/@ember/test-helpers/dom/-logging.ts
  addon/addon-test-support/@ember/test-helpers/dom/-target.ts
  addon/addon-test-support/@ember/test-helpers/dom/blur.ts
  addon/addon-test-support/@ember/test-helpers/dom/click.ts
  addon/addon-test-support/@ember/test-helpers/dom/double-click.ts
  addon/addon-test-support/@ember/test-helpers/dom/fill-in.ts
  addon/addon-test-support/@ember/test-helpers/dom/fire-event.ts
  addon/addon-test-support/@ember/test-helpers/dom/focus.ts
  addon/addon-test-support/@ember/test-helpers/dom/scroll-to.ts
  addon/addon-test-support/@ember/test-helpers/dom/select.ts
  addon/addon-test-support/@ember/test-helpers/dom/tab.ts
  addon/addon-test-support/@ember/test-helpers/dom/tap.ts
  addon/addon-test-support/@ember/test-helpers/dom/trigger-event.ts
  addon/addon-test-support/@ember/test-helpers/dom/trigger-key-event.ts
  addon/addon-test-support/@ember/test-helpers/dom/type-in.ts
  addon/addon-test-support/@ember/test-helpers/index.ts
  addon/addon-test-support/@ember/test-helpers/settled.ts
  addon/addon-test-support/@ember/test-helpers/setup-application-context.ts
  addon/addon-test-support/@ember/test-helpers/setup-context.ts
  addon/addon-test-support/@ember/test-helpers/setup-onerror.ts
  addon/addon-test-support/@ember/test-helpers/setup-rendering-context.ts
  addon/addon-test-support/@ember/test-helpers/teardown-context.ts
  addon/addon-test-support/@ember/test-helpers/test-metadata.ts
  addon/package.json
  addon/type-tests/tsconfig.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  type-tests/api.ts
  type-tests/package.json
  type-tests/tsconfig.json
  type-tests/types/dummy/index.d.ts
  type-tests/types/require.d.ts
Labels: internal
