Repository emberjs/ember-test-helpers, pull requests merged in 2025-01, with the labels that each got.

#1524 Widen test-waiters range
  .github/workflows/ci-build.yml
  addon/package.json
  addon/pnpm-lock.yaml
  test-app/config/ember-try.js
  test-app/package.json
  test-app/pnpm-lock.yaml
  test-app/tests/unit/settled-test.js
Labels: enhancement

#1530 v4: Widen test-waiters range
  .github/workflows/ci-build.yml
  addon/package.json
  addon/pnpm-lock.yaml
  test-app/config/ember-try.js
  test-app/package.json
  test-app/pnpm-lock.yaml
  test-app/tests/unit/settled-test.js
Labels: bug

#1531 make release-plan work for v4
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
Labels: internal

#1533 Make release-plan work for v3
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
Labels: internal
