Repository emberjs/ember-test-helpers, pull requests merged in 2025-03, with the labels that each got.

#1539 Cleanup some private API and now-unsupported usage
  addon/src/-internal/build-registry.ts
  addon/src/setup-rendering-context.ts
Labels: enhancement

#1540 Delete unused code in the test-app
  test-app/tests/helpers/destroy-app.js
  test-app/tests/helpers/module-for-acceptance.js
  test-app/tests/helpers/qunit-module-for.js
  test-app/tests/helpers/qunit-test-adapter.js
  test-app/tests/helpers/start-app.js
  test-app/tests/integration/.gitkeep
Labels: internal

#1542 backport globalThis setupContext
  addon-test-support/@ember/test-helpers/setup-context.ts
Labels: bug
